### PR TITLE
[develop] Mauricio - User controller tests

### PR DESCRIPTION
**Pull request by Snip-77**
HTTP methods tested:

-POST New user
-PUT Update user info
-PUT Update user rol

### CODE REVIEW

**Comment by marcos-x86** [comment]
@Snip-77 Please solve the merge conflicts.

**Review by marcos-x86 — CHANGES_REQUESTED** [review]
Please consider deleting the `bin/` folder and the `.classpath` and `.project` temporary files. Also, consider deleting all the commented test steps in feature files like lines 18, 19, and 23 in `createNewUser.feature`

**Comment by Snip-77** [comment]
> Please consider deleting the `bin/` folder and the `.classpath` and `.project` temporary files. Also, consider deleting all the commented test steps in feature files like lines 18, 19, and 23 in `createNewUser.feature`

**Review by marcos-x86 — APPROVED** [review]
LGTM!

**Pull request merged**
